baseURL: "/"
canonifyURLs: true
disableHugoGeneratorInject: true
enableRobotsTXT: true
languageCode: "en-US"
theme: "hugo-book"
timeout: "300s"
timeZone: "America/New_York"
title: "Anthrocon Docs"

cascade:
  _build:
    publishResources: false

frontmatter:
  date:
    - "date"
    - ":filename"
    - "publishDate"
    - "lastmod"
    - ":git"

  lastmod:
    - "lastmod"
    - ":git"

  publishDate:
    - ":default"
    - ":filename"

imaging:
  hint: "drawing"
  quality: 85
  resampleFilter: "Lanczos"

markup:
  goldmark:
    renderer:
      unsafe: true

  tableOfContents:
    startLevel: 1

menu:
  after:
    - name: "Anthrocon ◳"
      url: "https://www.anthrocon.org/"
      weight: 10

    - name: "GitHub ◳"
      url: "https://github.com/Anthrocon"
      weight: 20

params:
  BookTheme: "auto"
  BookRepo: "https://github.com/Anthrocon/docs"
  BookCommitPath: "commit"
  BookEditPath: "edit/main"
  BookDateFormat: "2006-01-02"
  BookComments: false
