name: Deploy Hugo site

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call:
    name: Call
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: Anthrocon/actions-deploy/.github/workflows/deploy.yaml@main
    with:
      hugo-version: "0.107.0"
    secrets: inherit
